baseURL = "https://insight-creative-2021-dev.netlify.app"
languageCode = "en-us"
title = "Insight Creative, Inc."
googleAnalytics = " "
enableRobotsTXT = true
disableAliases = true
summaryLength = 30
timeout = 200000

#################### default parameters ################################

[params]
  logo = "/images/insight-logo-white.svg"
  # Meta data
  description = "Site Description here"
  author = "Insight Creative, Inc."
  # Contact Information
  addressSt = "1816 Sal St."
  addressCity = "Green Bay, WI 54302"
  phone = "920-468-7459"
  email = "info@insightcreative.com"
  location = " "
  disallowSearchEngines = true
  minifyBundles = true

# add redirects/headers
  [outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.goldmark.renderer]
  unsafe= true

[menu]

  [[menu.main]]
    name = "Work"
    url  = "/work/"
    weight = 1

  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 2

  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3  

    [[menu.main]]
      parent = "Services"
      name = "Content"
      weight = 1
      url = "/services/copywriting-services/"

    [[menu.main]]
      parent = "Services"
      name = "Web"
      weight = 2
      url = "/services/web-design-development-services/"

    [[menu.main]]
      parent = "Services"
      name = "Digital"
      weight = 3
      url = "/services/digital-marketing-services/"

    [[menu.main]]
      parent = "Services"
      name = "Media"
      weight = 4
      url = "/services/media/"

    [[menu.main]]
      parent = "Services"
      name = "Design"
      weight = 5
      url = "/services/graphic-design-services/"

    [[menu.main]]
      parent = "Services"
      name = "Studio"
      weight = 6
      url = "/services/photography-videography-services/"

  [[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[related]
  includeNewer = true
  threshold = 80
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[[related.indices]]
  name = "tags"
  weight = 100
