[context.production.environment]
  HUGO_VERSION = "0.156.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.156.0"

[[redirects]]
  from = "/blog/marketing-agency-reasons/"
  to = "/blog/why-hiring-a-marketing-agency-is-the-smart-move/"

[[redirects]]
  from = "/about/theresa-tebon/"
  to = "/about/theresa-sawall/"

[[redirects]]
  from = "/blog/insight-creative-hires-mckenzie-kalscheuer-as-marketing-coordinator/"
  to = "/blog/"

[[redirects]]
  from = "/blog/insight-creative-hires-nicole-ehlers-promotes-molly-setzer/"
  to = "/blog/"

[[redirects]]
  from = "/blog/insight-promotes-sam-rowe-and-justin-parsons/"
  to = "/blog/"

[[redirects]]
  from = "/blog/internet-of-things-the-future-is-now/"
  to = "/blog/"

[[redirects]]
  from = "/blog/looking-on-the-bright-side-during-a-pandemic/"
  to = "/blog/"

[[redirects]]
  from = "/blog/insight-adds-two-employees-to-creative-team/"
  to = "/blog/"

[[redirects]]
  from = "/blog/insight-creative-inc-hires-account-executive-brian-brost/"
  to = "/blog/"

[[redirects]]
  from = "/blog/fueling-my-addiction/"
  to = "/blog/"

[[redirects]]
  from = "/blog/insight-designer-paints-golden-helmet-for-super-bowl-50/"
  to = "/blog/"

[[redirects]]
  from = "/blog/the-modern-collaboration-toolkit/"
  to = "/blog/"