const autoprefixer = require('autoprefixer')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
  plugins: [
    autoprefixer(),
    purgecss({
      content: [
        './layouts/**/*.html',
        './layouts/**/*.svg',
        './content/**/*.md',
      ],
      safelist: [
            'sub-menu-active',
            'active',
            'is-active',
            'slider__dots',
            'slider__dot',
            'is-selected',
            'nav-open',
            'collapse',
            'expand',
            'list-open',
            'is-transitioning',
            'btn-inactive',
            'has-search-open',
            'services-hero',
            'content-hero',
            'design-hero',
            'web-hero',
            'studio-hero',
            'digital-hero',
            'media-hero',
            'content-intro',
            'web-intro',
            'media-intro',
            'digital-intro',
            'design-intro',
            'studio-intro',
            'aa-Form',
            'aa-Autocomplete',
            'aa-InputWrapperPrefix',
            'aa-InputWrapper',
            'aa-Input',
            'aa-SubmitIcon',
            'aa-ClearIcon',
            'aa-InputWrapperSuffix',
            'aa-DetachedFormContainer',
            'ctct-form-embed',
            'form_0',
            'ctct-form-defaults',
            'ctct-form-label',
            'ctct-form-custom',
            'ctct-form-required',
            'ctct-form-element',
            'ctct-gdpr-text',
            'ctct-form-button',
            'g-recaptcha',
            'nicole-ehlers',
            'cindy-struensee',
            'theresa-tebon',
            'theresa-sawall',
            'olivia-biskobing',
            'chue-vang',
            'melissa-gorzelanczyk',
            'mckenzie-kalscheuer',
            'emphasis-underline--secondary',
            'new-zoo--adventure-park-canopy-tour-signage',
            'verve-public-relations-campaign',
            'insight-promotes-niki-petit-to-vice-president-and-adds-melissa-gorzelanczyk-to-creative-team',
            'parent-page-work'
          ],
    }),
  ],
}
